const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class E{constructor(){this.value='';this.children=[];this.events={};this.dataset={};this.disabled=false;this.hidden=false;}append(...c){this.children.push(...c);}replaceChildren(...c){this.children=c;}addEventListener(k,f){this.events[k]=f;}setAttribute(){}showModal(){this.open=true;}close(){this.open=false;}}
(async()=>{
const els=new Map(),get=k=>{if(!els.has(k))els.set(k,new E());return els.get(k);},fields=Object.fromEntries(['trip_id','driver_id','vehicle_id','notes'].map(k=>[k,new E()]));get('assignmentForm').elements={namedItem:k=>fields[k]};
const events={},writes=[],redirects=[];let role='STAFF',mode='normal',failure=false;
const a={assignment_id:'9007199254740993',trip_id:'1',driver_id:'10',vehicle_id:'20',assigned_by:'5',driver_code:'TX10',driver_name:'<script>',license_plate:'51C',assigned_at:'2026-10-07',status:'assigned',notes:null,start_location:'A',end_location:'B'};
const sandbox={document:{getElementById:get,createElement:()=>new E(),createTextNode:t=>({textContent:t})},window:{addEventListener:(k,f)=>events[k]=f},location:{href:'http://localhost/TRANSPORT_MANAGEMENT/frontend/transport/assignment.html',replace:u=>redirects.push(u)},sessionStorage:{removeItem(){}},URL,URLSearchParams,TextEncoder,fetch:async(url,o)=>{assert.equal(o.credentials,'same-origin');assert.equal(o.cache,'no-store');const route=url.searchParams.get('route');if(o.method!=='GET'){writes.push({route,method:o.method,id:url.searchParams.get('id'),body:o.body?JSON.parse(o.body):null});return {ok:!failure,status:failure?409:200,json:async()=>({success:!failure,message:'Tài nguyên đã được phân công',data:a})};}let data;if(route==='/api/me')data={role,status:1,full_name:'STAFF'};else if(route.endsWith('/options'))data={trips:[{id:'1',status:'PLANNED',start_location:'A',end_location:'B'},{id:'2',status:'PLANNED',start_location:'C',end_location:'D'}],drivers:[{driver_id:'10',driver_code:'TX10',full_name:'A',status:'on_trip',license_expiry:null},{driver_id:'11',driver_code:'TX11',full_name:'B',status:'available',license_expiry:null}],vehicles:[{vehicle_id:'20',license_plate:'51C',status:'on_trip'},{vehicle_id:'21',license_plate:'52C',status:'available'}],active:[a]};else if(route.endsWith('/show'))data=a;else data=mode==='empty'?[]:[a];return {ok:mode!=='error',status:mode==='error'?500:200,json:async()=>({success:mode!=='error',data})};}};
vm.runInNewContext(fs.readFileSync('frontend/js/assignment.js','utf8'),sandbox);const settle=async()=>{for(let i=0;i<10;i++)await new Promise(r=>setImmediate(r));};await settle();assert.equal(get('addButton').disabled,false);assert.equal(get('metric-assigned').textContent,1);assert.equal(get('assignmentRows').children[0].children[1].textContent,'TX10 · <script>');
await get('addButton').events.click();await settle();assert.equal(get('assignmentDialog').open,true);assert.equal(fields.driver_id.children.length,2);assert.equal(fields.trip_id.children.length,2); // only unoccupied trip 2 and driver 11
fields.trip_id.value='2';fields.driver_id.value='11';fields.vehicle_id.value='21';fields.notes.value='test';await get('assignmentForm').events.submit({preventDefault(){}});assert.equal(writes.at(-1).method,'POST');assert.equal(writes.at(-1).body.assigned_by,undefined);
async function click(action){await get('assignmentRows').events.click({target:{closest:()=>({dataset:{id:a.assignment_id,action}})}});}
await click('view');assert.equal(get('assignmentFields').hidden,true);assert.equal(get('assignmentDetails').children.length,13);
await click('replace');assert.equal(fields.trip_id.disabled,false);fields.trip_id.value='2';await get('assignmentForm').events.submit({preventDefault(){}});assert.equal(writes.at(-1).method,'PUT');assert.equal(writes.at(-1).id,a.assignment_id);assert.equal(writes.at(-1).body.trip_id,'2');
const before=writes.length;await click('cancel');assert.equal(writes.length,before);assert.equal(get('confirmDialog').open,true);failure=true;await get('confirmButton').events.click();assert.equal(get('confirmDialog').open,true);assert.match(get('confirmMessage').textContent,/phân công/);failure=false;await get('confirmButton').events.click();assert.equal(writes.at(-1).route,'/api/assignments/cancel');await click('complete');await get('confirmButton').events.click();assert.equal(writes.at(-1).route,'/api/assignments/complete');
mode='empty';await get('refreshButton').events.click();assert.match(get('assignmentRows').children[0].children[0].textContent,/Không có/);mode='error';await get('refreshButton').events.click();assert.equal(get('listRetry').hidden,false);mode='normal';role='CUSTOMER';events.pagehide();events.pageshow({persisted:true});await settle();assert.equal(get('addButton').disabled,true);
console.log('PASS: Assignment frontend mock: session/roles, stats, empty/error, resource exclusion, create/view/replace cross-trip, confirm complete/cancel, 409, BIGINT and text safety. No HTTP writes.');
})().catch(e=>{console.error(e);process.exitCode=1;});
