(() => {
'use strict';
const $=id=>document.getElementById(id),form=$('assignmentForm'),field=k=>form.elements.namedItem(k),endpoint=new URL('../../backend/public/index.php',location.href);
const labels={assigned:'Đang hiệu lực',completed:'Hoàn tất',cancelled:'Đã hủy'};
function icon(name){const i=document.createElement('i');i.className='fa-solid fa-'+name;i.setAttribute('aria-hidden','true');return i;}
function statusBadge(status){const badge=document.createElement('span');badge.className='drivers-badge '+(Object.hasOwn(labels,status)?status:'');badge.append(icon(({assigned:'truck',completed:'circle-check',cancelled:'ban'})[status]||'circle-question'),document.createTextNode(labels[status]??status));return badge;}
let ready=false,saving=false,selected=null,pending=null,options=null,revision=0,request=0;
function msg(id,text='',error=false){$(id).textContent=text;$(id).className=text?'drivers-message'+(error?' error':''):'';}
function lock(){ready=false;request++;$('addButton').disabled=true;$('assignmentDialog').close();$('confirmDialog').close();tableMessage('Chưa xác thực quyền quản lý phân công.');}
async function api(route,method='GET',body,params={}){
 const url=new URL(endpoint);url.search=new URLSearchParams({route,...params});let response;
 try{response=await fetch(url,{method,credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});}catch{throw new Error('Không thể kết nối máy chủ. Vui lòng thử lại.');}
 if(response.status===401||response.status===403){lock();if(response.status===401)location.replace('../customer/login.html');}
 let result;try{result=await response.json();}catch{throw new Error('Phản hồi không hợp lệ. Vui lòng thử lại.');}
 if(!response.ok||!result?.success)throw new Error(response.status>=500?'Không thể xử lý phân công lúc này. Vui lòng thử lại.':result?.message||'Yêu cầu thất bại.');return result.data;
}
function cell(row,text,label){const td=document.createElement('td');td.dataset.label=label;td.textContent=text??'—';row.append(td);return td;}
function tableMessage(text,loading=false){const tr=document.createElement('tr'),td=cell(tr,text,'');td.colSpan=8;td.className='drivers-empty'+(loading?' loading':'');$('assignmentRows').replaceChildren(tr);}
async function load(){if(!ready)return;const seq=++request;tableMessage('Đang tải…',true);$('listRetry').hidden=true;try{
 const rows=await api('/api/assignments','GET',null,{search:$('search').value.trim(),status:$('statusFilter').value});if(seq!==request||!ready)return;if(!Array.isArray(rows))throw new Error('Danh sách không hợp lệ.');$('assignmentRows').replaceChildren();
 for(const a of rows){const tr=document.createElement('tr');for(const [text,label] of [[`#${a.trip_id}: ${a.start_location??'Không tìm thấy chuyến'} → ${a.end_location??'—'}`,'Chuyến'],[`${a.driver_code??'—'} · ${a.driver_name??'—'}`,'Tài xế'],[a.license_plate,'Phương tiện'],[a.assigned_by_name??`ID ${a.assigned_by??'—'}`,'Người phân công'],[a.assigned_at,'Thời điểm'],[labels[a.status]??a.status,'Trạng thái'],[a.notes,'Ghi chú']]){const td=cell(tr,text,label);if(label==='Trạng thái')td.replaceChildren(statusBadge(a.status));}
 const actions=document.createElement('div');actions.className='drivers-row-actions';cell(tr,'','Thao tác').replaceChildren(actions);
 for(const [action,title] of [['view','Xem'],...(a.status==='assigned'?[['replace','Đổi'],['complete','Hoàn tất'],['cancel','Hủy']]:[])]){const b=document.createElement('button');b.type='button';b.dataset.action=action;b.dataset.id=String(a.assignment_id);b.append(icon(({view:'eye',replace:'pen-to-square',complete:'circle-check',cancel:'ban'})[action]),document.createTextNode(title));b.setAttribute('aria-label',`${title} phân công ${a.assignment_id}`);actions.append(b);}$('assignmentRows').append(tr);}
 if(!rows.length)tableMessage('Không có phân công phù hợp.');$('resultCount').textContent=`Có ${rows.length} phân công phù hợp.`;
 }catch(e){if(seq===request){tableMessage(e.message);$('resultCount').textContent='Không tải được danh sách.';$('listRetry').hidden=false;}}
}
async function stats(){try{const rows=await api('/api/assignments');if(!ready)return;if(!Array.isArray(rows))throw new Error('Thống kê không hợp lệ.');$('metric-total').textContent=rows.length;for(const s of Object.keys(labels))$('metric-'+s).textContent=rows.filter(a=>a.status===s).length;$('statsMessage').textContent='Thống kê toàn bộ lịch sử, không phụ thuộc bộ lọc.';}catch(e){$('statsMessage').textContent=e.message;}}
async function refresh(){if(!ready)return;await Promise.all([load(),stats()]);}
function fillSelect(key,rows,value,title){const s=field(key);s.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='Chọn '+title;s.append(empty);for(const row of rows){const o=document.createElement('option');o.value=String(row[key]??row.id);o.textContent=key==='trip_id'?`#${row.id}: ${row.start_location} → ${row.end_location} · ${row.status}`:key==='driver_id'?`${row.driver_code} · ${row.full_name}`:`${row.license_plate} · ${row.vehicle_type} · ${row.capacity} kg`;s.append(o);}s.value=value??'';}
function tripInfo(){const t=options?.trips.find(t=>String(t.id)===field('trip_id').value);$('tripInfo').textContent=t?`Chuyến #${t.id}: ${t.start_location} → ${t.end_location}. Khởi hành: ${t.start_time??'Chưa có'}. Trạng thái chuyến: ${t.status}.`:'Chỉ chọn chuyến PLANNED/IN_PROGRESS. Không có dữ liệu khả dụng thì không tạo phân công.';}
async function open(a=null,view=false){if(!ready||saving)return;selected=a;msg('formMessage');$('assignmentDetails').replaceChildren();$('assignmentFields').hidden=view;$('assignmentDetails').hidden=!view;$('saveButton').hidden=view;$('dialogTitle').textContent=view?'Chi tiết phân công':a?'Đổi phân công':'Tạo phân công';
 if(view){for(const [key,title] of [['assignment_id','Mã phân công'],['trip_id','Chuyến'],['start_location','Điểm đi'],['end_location','Điểm đến'],['trip_status','Trạng thái chuyến'],['driver_name','Tài xế'],['license_plate','Phương tiện'],['assigned_by_name','Người phân công'],['assigned_at','Phân công lúc'],['completed_at','Hoàn tất lúc'],['cancelled_at','Hủy lúc'],['status','Trạng thái phân công'],['notes','Ghi chú']]){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=title;if(key==='status')dd.append(statusBadge(a[key]));else dd.textContent=a[key]??'—';div.append(dt,dd);$('assignmentDetails').append(div);}}
 else{options=await api('/api/assignments/options');if(!ready)return;const active=options.active.filter(x=>!a||String(x.assignment_id)!==String(a.assignment_id));const ids=k=>new Set(active.map(x=>String(x[k])));
 const trips=options.trips.filter(t=>!ids('trip_id').has(String(t.id)));const drivers=options.drivers.filter(d=>(d.status==='available'||(a&&String(d.driver_id)===String(a.driver_id)))&&!ids('driver_id').has(String(d.driver_id))&&(!d.license_expiry||d.license_expiry>=[new Date().getFullYear(),String(new Date().getMonth()+1).padStart(2,'0'),String(new Date().getDate()).padStart(2,'0')].join('-')));const vehicles=options.vehicles.filter(v=>(v.status==='available'||(a&&String(v.vehicle_id)===String(a.vehicle_id)))&&!ids('vehicle_id').has(String(v.vehicle_id)));
 fillSelect('trip_id',trips,a?.trip_id,'chuyến');fillSelect('driver_id',drivers,a?.driver_id,'tài xế');fillSelect('vehicle_id',vehicles,a?.vehicle_id,'phương tiện');field('trip_id').disabled=false;field('notes').value=a?.notes??'';for(const key of ['trip_id','driver_id','vehicle_id','notes'])$('error-'+key).textContent='';tripInfo();}
 $('assignmentDialog').showModal();}
$('addButton').addEventListener('click',()=>open().catch(e=>msg('pageMessage',e.message,true)));
field('trip_id').addEventListener('change',tripInfo);
$('assignmentRows').addEventListener('click',async event=>{const b=event.target.closest('button[data-action]');if(!b||!ready||saving)return;try{if(['view','replace'].includes(b.dataset.action)){const a=await api('/api/assignments/show','GET',null,{id:b.dataset.id});await open(a,b.dataset.action==='view');}else{pending={id:b.dataset.id,action:b.dataset.action};$('confirmTitle').textContent=pending.action==='complete'?'Hoàn tất phân công':'Hủy phân công';$('confirmDescription').textContent=`Xác nhận ${pending.action==='complete'?'hoàn tất':'hủy'} phân công #${pending.id}? Không đổi trạng thái chuyến/đơn hàng; lịch sử được giữ.`;msg('confirmMessage');$('confirmDialog').showModal();}}catch(e){msg('pageMessage',e.message,true);}});
form.addEventListener('submit',async event=>{event.preventDefault();if(!ready||saving||$('saveButton').hidden)return;const data={};let valid=true;for(const key of ['trip_id','driver_id','vehicle_id']){data[key]=field(key).value;$('error-'+key).textContent=data[key]?'':'Vui lòng chọn thông tin này.';if(!data[key])valid=false;}data.notes=field('notes').value.trim()||null;$('error-notes').textContent='';if(data.notes&&new TextEncoder().encode(data.notes).length>65535){$('error-notes').textContent='Ghi chú vượt 65535 byte.';valid=false;}if(!valid)return;saving=true;$('saveButton').disabled=true;
 try{await api('/api/assignments',selected?'PUT':'POST',data,selected?{id:String(selected.assignment_id)}:{});$('assignmentDialog').close();msg('pageMessage',selected?'Đã đổi phân công; giữ lịch sử bản cũ.':'Tạo phân công thành công.');await refresh();}catch(e){msg('formMessage',e.message,true);}finally{saving=false;$('saveButton').disabled=!ready;}});
$('confirmButton').addEventListener('click',async()=>{if(!ready||saving||!pending)return;saving=true;$('confirmButton').disabled=true;try{await api('/api/assignments/'+pending.action,'PUT',null,{id:pending.id});$('confirmDialog').close();pending=null;msg('pageMessage','Cập nhật phân công thành công.');await refresh();}catch(e){msg('confirmMessage',e.message,true);}finally{saving=false;$('confirmButton').disabled=!ready;}});
for(const id of ['closeDialog','cancelDialog'])$(id).addEventListener('click',()=>{if(!saving)$('assignmentDialog').close();});$('closeConfirm').addEventListener('click',()=>{if(!saving)$('confirmDialog').close();});for(const id of ['assignmentDialog','confirmDialog'])$(id).addEventListener('cancel',event=>{if(saving)event.preventDefault();});
$('filterForm').addEventListener('submit',event=>{event.preventDefault();load();});$('statusFilter').addEventListener('change',load);$('resetFilter').addEventListener('click',()=>{$('search').value='';$('statusFilter').value='';load();});$('refreshButton').addEventListener('click',()=>ready?refresh():boot());$('listRetry').addEventListener('click',load);
$('logoutButton').addEventListener('click',async()=>{if(saving)return;try{await api('/api/logout','POST');revision++;lock();try{sessionStorage.removeItem('user');}catch{}location.replace('../customer/login.html');}catch(e){msg('pageMessage',e.message,true);}});
async function boot(){const current=++revision;lock();for(const key of ['total',...Object.keys(labels)])$('metric-'+key).textContent='—';try{const user=await api('/api/me');if(current!==revision)return;if(!['ADMIN','STAFF'].includes(user?.role)||Number(user.status)!==1)throw new Error('Chỉ ADMIN/STAFF đang hoạt động được quản lý phân công.');ready=true;$('currentUser').textContent=user.full_name||user.username;$('addButton').disabled=false;msg('pageMessage');await refresh();}catch(e){if(current===revision)msg('pageMessage',e.message,true);}}
window.addEventListener('pagehide',()=>{revision++;lock();});window.addEventListener('pageshow',event=>{if(event.persisted)boot();});boot();
})();
